// Runtime QA for the working Anamarija architecture spec. This is a modelling regression check, not certification.
const range=(a,b)=>[Math.min(a,b),Math.max(a,b)];const contains=(a,b,x,t=.03)=>{const[lo,hi]=range(a,b);return x>=lo-t&&x<=hi+t};
function deckCovers(c,x,z,t=.03){return x>=c.x-c.width/2-t&&x<=c.x+c.width/2+t&&z>=c.z-c.depth/2-t&&z<=c.z+c.depth/2+t;}
export function auditArchitecture(spec){const issues=[],info=[],walls=spec.walls||[],openings=spec.openings||[],glazing=spec.glazing||[],ext=walls.filter(w=>w.zone==='external'),house=spec.house||{},XW=-house.width/2,XE=house.width/2,ZN=house.z-house.depth/2,ZS=house.z+house.depth/2;
 for(const[x,z,name]of[[XW,ZN,'south-west'],[XE,ZN,'south-east'],[XW,ZS,'north-west'],[XE,ZS,'north-east']]){const xw=ext.some(w=>w.axis==='x'&&Math.abs(w.fixed-z)<.12&&contains(w.a,w.b,x,.12)),zw=ext.some(w=>w.axis==='z'&&Math.abs(w.fixed-x)<.12&&contains(w.a,w.b,z,.12));if(!xw||!zw)issues.push({severity:'error',code:'OPEN_CORNER',message:`Exterior ${name} corner is not joined.`});}
 // Side glazing must be recognised as a cut-out even while the canonical wall is represented as one span; renderer/collision split it around sill/head.
 for(const g of glazing.filter(g=>g.axis==='z')){const host=ext.find(w=>w.axis==='z'&&Math.abs(w.fixed-g.fixed)<.12&&contains(w.a,w.b,g.a)&&contains(w.a,w.b,g.b));if(!host)issues.push({severity:'error',code:'SIDE_GLAZING_HOST',message:`${g.id} has no host façade wall.`});if((g.sill??0)+g.height>3.25)issues.push({severity:'error',code:'GLAZING_HEAD',message:`${g.id} exceeds working façade head.`});}
 // Zoned ceilings: sample each room centre instead of requiring one unrealistic full-envelope deck.
 const ceilings=spec.ceilings||[];for(const r of spec.rooms||[]){const x=r.x,z=r.z+house.z;if(!ceilings.some(c=>deckCovers(c,x,z)))issues.push({severity:'error',code:'CEILING_ROOM_COVERAGE',message:`No ceiling zone covers room ${r.id} centre.`});}
 for(const t of spec.ceilingTransitions||[])if(!(t.top>t.bottom))issues.push({severity:'error',code:'CEILING_TRANSITION',message:`Invalid ceiling transition ${t.id}.`});
 const rv=spec.roof?.volumes||[],minX=rv.length?Math.min(...rv.map(v=>v.x-v.width/2)):Infinity,maxX=rv.length?Math.max(...rv.map(v=>v.x+v.width/2)):-Infinity,minZ=rv.length?Math.min(...rv.map(v=>v.z-v.depth/2)):Infinity,maxZ=rv.length?Math.max(...rv.map(v=>v.z+v.depth/2)):-Infinity;if(!rv.length||minX>XW||maxX<XE||minZ>ZN||maxZ<ZS)issues.push({severity:'error',code:'ROOF_COVERAGE',message:'Roof volumes do not cover the complete working house bounding envelope.'});
 const a=spec.accessibility||{},portal=openings.find(o=>o.id==='terrace-portal');if((a.internalDoorClearTarget||0)<.90)issues.push({severity:'error',code:'DOOR_CLEARANCE',message:'Internal door clear-width target is below 0.90m.'});if((a.turningDiameterTarget||0)<1.50)issues.push({severity:'warning',code:'TURNING_DIAMETER',message:'Wheelchair turning target is below 1.50m.'});if(!portal||portal.clearWidth<1.10)issues.push({severity:'error',code:'TERRACE_PORTAL_WIDTH',message:'Terrace portal does not retain the working accessible clear width.'});if(!portal?.flushThreshold||(spec.terrace?.thresholdMax??1)>.015)issues.push({severity:'warning',code:'TERRACE_THRESHOLD',message:'Terrace threshold is above the working flush-threshold target.'});
 info.push({code:'PROVISIONAL_GEOMETRY',message:'Coordinates remain working-design geometry pending architect/engineer drawings.'});return{ok:!issues.some(i=>i.severity==='error'),issues,info,checkedAt:new Date().toISOString()};}
export function reportArchitectureAudit(result,logger=console){const fn=result.ok?'info':'warn';logger[fn]?.(`[architecture QA] ${result.ok?'PASS':'FAIL'} · ${result.issues.length} issue(s)`);for(const i of result.issues)(i.severity==='error'?logger.error:logger.warn)?.(`[architecture QA] ${i.code}: ${i.message}`);return result;}
